/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package week.pkg6.lab;

import java.awt.Color;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emoha
 */
public class GradeManagment extends javax.swing.JFrame {

    /**
     * Creates new form GradeManagment
     */
    public GradeManagment() {
        initComponents();
        // center the form
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblTest1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        lblTest3 = new javax.swing.JLabel();
        txtTest1 = new javax.swing.JTextField();
        txtTest2 = new javax.swing.JTextField();
        txtTest3 = new javax.swing.JTextField();
        btnAddStudent = new javax.swing.JButton();
        btnDisplayAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaStudents = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        lblLogo = new javax.swing.JLabel();
        lblStudentID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grade Managment System");

        lblName.setBackground(new java.awt.Color(0, 204, 204));
        lblName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 204, 204));
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lblTest1.setBackground(new java.awt.Color(0, 204, 204));
        lblTest1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTest1.setForeground(new java.awt.Color(0, 204, 204));
        lblTest1.setText("Test1:");

        lblName2.setBackground(new java.awt.Color(0, 204, 204));
        lblName2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblName2.setForeground(new java.awt.Color(0, 204, 204));
        lblName2.setText("Test 2:");

        lblTest3.setBackground(new java.awt.Color(0, 204, 204));
        lblTest3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTest3.setForeground(new java.awt.Color(0, 204, 204));
        lblTest3.setText("Test 3:");

        txtTest1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTest2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtTest3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnAddStudent.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnDisplayAll.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDisplayAll.setText("Display All");
        btnDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAllActionPerformed(evt);
            }
        });

        txaStudents.setColumns(20);
        txaStudents.setRows(5);
        jScrollPane1.setViewportView(txaStudents);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStudents);

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/week/pkg6/lab/cong-clipart-6.jpg"))); // NOI18N

        lblStudentID.setBackground(new java.awt.Color(0, 204, 204));
        lblStudentID.setFont(new java.awt.Font("Segoe UI", 0, 3)); // NOI18N
        lblStudentID.setForeground(new java.awt.Color(0, 204, 204));
        lblStudentID.setText("StudentID:");
        lblStudentID.setAutoscrolls(true);
        lblStudentID.setEnabled(false);
        lblStudentID.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTest1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTest2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTest3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDisplayAll, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStudentID))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStudentID)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTest1)
                                    .addComponent(txtTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName2)
                                    .addComponent(txtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTest3)
                                    .addComponent(txtTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddStudent)
                            .addComponent(btnDisplayAll))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllActionPerformed
        // TODO add your handling code here:
        //show ouput to the text area
        txaStudents.setText("Name"+"\t"+"Test1"+"\t"+"Test2"+"\t"+"Test3"+"\t"+"Average"+"\t"+"Grade"+"\n");
        //read the student records
        StudentDB db = new StudentDB();
        try {
            ArrayList<Student> data = db.getAll();
            DecimalFormat fmt = new DecimalFormat("0.0");
            for (int i = 0; i < data.size(); i++) {
                Student stu = data.get(i);
                txaStudents.append(stu.getName() + "\t" + stu.getTest1()+ "\t"+ stu.getTest2()+"\t"+stu.getTest3()+"\t"+
                        fmt.format(stu.calculateAverage())+"\t"+stu.calculateLetterGrade() +"\n");
                
            }
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "Error, Database driver not found, "
                     + "error:3.", "Driver not found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: "+
                    ex.getMessage()+" error:4", 
                     "Database error", JOptionPane.ERROR_MESSAGE);
        }
        //========================================//
        //display records on a JTable
        //show headings
        DefaultTableModel tblModel = new DefaultTableModel();
        tblStudents.setModel(tblModel);
        String[] colTitles = {"Name","Test1","Test2","Test3","Average","Grade"};
        tblModel.setColumnIdentifiers(colTitles);
        
        //read student records
        StudentDB db2 = new StudentDB();
        try {
            ArrayList<Student> records = db2.getAll();
            DecimalFormat fmt2 = new DecimalFormat("0.0");
            for (int i = 0; i < records.size(); i++) {
                Student stu = records.get(i);
                
                Object[] row = {stu.getName(),stu.getTest1(),stu.getTest2(),stu.getTest3(),
                fmt2.format(stu.calculateAverage()),stu.calculateLetterGrade()};
                
                tblModel.addRow(row);
            }
        } catch (ClassNotFoundException ex) {
             JOptionPane.showMessageDialog(this, "Error, Database driver not found, "
                     + "error:5", "Driver not found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: "+
                    ex.getMessage()+" error:6", 
                     "Database error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDisplayAllActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
            // TODO add your handling code here:
        // get student info
        String stuName = txtName.getText();
        double test1 = Double.parseDouble(txtTest1.getText());
        double test2 = Double.parseDouble(txtTest2.getText());
        double test3 = Double.parseDouble(txtTest3.getText());
        //create student object
        Student stu = new Student(0, stuName, test1, test2, test3);
        //add student to teh database using StudentDB object
        StudentDB db = new StudentDB();
        try {
            db.add(stu);
            JOptionPane.showMessageDialog(this, "Record was written to the database");
            // clear the form
            txtName.setText("");
            txtTest1.setText("");
            txtTest2.setText("");
            txtTest3.setText("");
            txtName.requestFocus();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error, Database driver not found, "
                    + "error:1"
                    , "Driver not found", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: "+
                    ex.getMessage()+" error:2", 
                     "Database error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeManagment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GradeManagment().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnDisplayAll;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblStudentID;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest3;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextArea txaStudents;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTest1;
    private javax.swing.JTextField txtTest2;
    private javax.swing.JTextField txtTest3;
    // End of variables declaration//GEN-END:variables
}
